# Generated by Django 3.2.5 on 2021-08-13 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0006_auto_20210809_0208'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_list',
            name='kakaotalkid',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
